# support for flat assembler

SET(ASM_DIALECT "-FASM")
SET(CMAKE_ASM${ASM_DIALECT}_SOURCE_FILE_EXTENSIONS s;S;asm)
INCLUDE(CMakeASMInformation)
SET(CMAKE_ASM-FASM_COMPILE_OBJECT "<CMAKE_ASM-FASM_COMPILER> <SOURCE> <OBJECT>")
SET(ASM_DIALECT)
